# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'

services:
  cli:
    image: hyperledger/fabric-tools:1.4.4
    tty: true
    stdin_open: true

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}
    environment:
      # - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - chaincode:/opt/gopath/src/github.com/chaincode
        - crypto:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts

    networks:
      hlf:
        aliases:
          - cli

volumes:
  artifacts:
    name: cli_artifacts
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/channel-artifacts"

  scripts:
    name: cli_scripts
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/scripts"

  crypto:
    name: cli_crypto
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/crypto-config"

  chaincode:
    name: cli_chaincode
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/chaincode"

networks:
  hlf:
    name: ${NETWORK}
    external: true      