version: "3.7"

services:
  couchdb:
    image: hyperledger/fabric-couchdb:0.4.18
    networks:
      hlf:
        aliases:
          - couchdb.${PEER_HOSTNAME}.${PEER_DOMAIN}

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}

    ports:
      - 8984:5984

    environment:
      - COUCHDB_USER=  
      - COUCHDB_PASSWORD=

  peer:
    image: hyperledger/fabric-peer:1.4.4
    networks:
      hlf:
        aliases:
          - ${PEER_HOSTNAME}.${PEER_DOMAIN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${NODE_HOSTNAME}
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=${FABRIC_LOGGING_SPEC}
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=${PEER_HOSTNAME}.${PEER_DOMAIN}
      - CORE_PEER_ADDRESS=${PEER_HOSTNAME}.${PEER_DOMAIN}:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=${PEER_HOSTNAME}.${PEER_DOMAIN}:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${PEER_HOSTNAME}.${PEER_DOMAIN}:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:9051
      - CORE_PEER_LOCALMSPID=${CORE_PEER_LOCALMSPID}
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.${PEER_HOSTNAME}.${PEER_DOMAIN}:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${NETWORK}
    volumes:
      - /var/run/:/host/var/run/
      - msp:/etc/hyperledger/fabric/msp
      - tls:/etc/hyperledger/fabric/tls
    ports:
      - "10051:10051"
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on: 
      - couchdb
    command: peer node start

volumes:
  msp:
    name: ${PEER_HOSTNAME}${PEER_DOMAIN}msp
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/crypto-config/peerOrganizations/${PEER_DOMAIN}/peers/${PEER_HOSTNAME}.${PEER_DOMAIN}/msp"
  tls:
    name: ${PEER_HOSTNAME}${PEER_DOMAIN}tls
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDR}"
      device: ":${NFS_PATH}/crypto-config/peerOrganizations/${PEER_DOMAIN}/peers/${PEER_HOSTNAME}.${PEER_DOMAIN}/tls"

networks:
  hlf:
    name: ${NETWORK}
    external: true
